// Application seed data — merges identity + M1 regulatory defaults + M2 selection defaults

export const APPLICATIONS = [
  {
    id: 'supermarket',
    labelFr: 'Supermarche / Commerce',
    labelEn: 'Supermarket / Retail',
    icon: '🛒',
    descFr: 'Supermarches, magasins, vitrines refrigerees, meubles froids',
    descEn: 'Supermarkets, retail stores, refrigerated displays, cold cabinets',
    // M1 defaults
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    // M2 defaults
    productFamilies: JSON.stringify(['GLACIAR MIDI']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R744', 'R32', 'R134A', 'R404A', 'R449A', 'R410A', 'R407F']),
    applicableSpaceTypes: JSON.stringify(['sales_area', 'cold_room', 'machinery_room', 'cold_storage', 'loading_dock']),
    sortOrder: 1,
  },
  {
    id: 'cold_room',
    labelFr: 'Chambre froide / Entrepot',
    labelEn: 'Cold Room / Warehouse',
    icon: '🧊',
    descFr: 'Chambres froides, entrepots, stockage froid, brasseries, systemes eau/saumure',
    descEn: 'Cold rooms, warehouses, cold storage, breweries, water/brine systems',
    accessCategory: 'c',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['GLACIAR MIDI', 'X5 Direct Sensor Module', 'X5 Remote Sensor']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm', R717: '0-100ppm' }),
    suggestedGases: JSON.stringify(['R744', 'R717', 'R32', 'R134A', 'R404A', 'R449A']),
    applicableSpaceTypes: JSON.stringify(['cold_room', 'cold_storage', 'machinery_room']),
    sortOrder: 2,
  },
  {
    id: 'machinery_room',
    labelFr: 'Salle des machines',
    labelEn: 'Machine Room',
    icon: '⚙️',
    descFr: 'Salles des machines, compresseurs, refroidissement process industriel, centrales electriques',
    descEn: 'Machinery rooms, compressor rooms, industrial process cooling, power plants',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5 Direct Sensor Module', 'X5 Remote Sensor', 'GLACIAR MIDI']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R744', 'R717', 'R290', 'R32', 'R134A']),
    applicableSpaceTypes: JSON.stringify(['machinery_room', 'basement_machinery', 'technical_room']),
    sortOrder: 3,
  },
  {
    id: 'hotel',
    labelFr: 'Confort / Espace occupe',
    labelEn: 'Comfort / Occupied Space',
    icon: '🏨',
    descFr: 'Hotels, bureaux, residences, ecoles, espaces occupes avec VRF/split',
    descEn: 'Hotels, offices, residences, schools, occupied spaces with VRF/split systems',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['GLACIAR RM']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['R32', 'R410A']),
    applicableSpaceTypes: JSON.stringify(['hotel_room', 'office', 'technical_room', 'rooftop']),
    sortOrder: 4,
  },
  {
    id: 'hospital',
    labelFr: 'Hopital / Sante',
    labelEn: 'Hospital / Healthcare',
    icon: '🏥',
    descFr: 'Hopitaux, cliniques, etablissements de sante, blocs operatoires',
    descEn: 'Hospitals, clinics, healthcare facilities, operating rooms',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['GLACIAR RM', 'GLACIAR MIDI']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['R32', 'R410A', 'R744']),
    applicableSpaceTypes: JSON.stringify(['office', 'cold_room', 'machinery_room', 'technical_room']),
    sortOrder: 5,
  },
  {
    id: 'public_venue',
    labelFr: 'Lieu public / Arena',
    labelEn: 'Public Venue / Arena',
    icon: '🏟️',
    descFr: 'Patinoires, stades, arenas, navires de croisiere, lieux publics',
    descEn: 'Ice rinks, stadiums, arenas, cruise ships, public venues',
    accessCategory: 'a',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['X5 Direct Sensor Module', 'X5 Remote Sensor', 'GLACIAR MIDI']),
    defaultRanges: JSON.stringify({ R717: '0-500ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R717', 'R744', 'R32']),
    applicableSpaceTypes: JSON.stringify(['ice_rink', 'machinery_room', 'technical_room']),
    sortOrder: 6,
  },
  {
    id: 'data_center',
    labelFr: 'Data Center',
    labelEn: 'Data Center',
    icon: '🖥️',
    descFr: 'Refroidissement serveurs, salles informatiques',
    descEn: 'Server cooling, IT rooms',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: false,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['GLACIAR MIDI', 'X5 Direct Sensor Module', 'X5 Remote Sensor']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R32', 'R134A', 'R744', 'R410A']),
    applicableSpaceTypes: JSON.stringify(['office', 'machinery_room', 'technical_room']),
    sortOrder: 7,
  },
  {
    id: 'heat_pump',
    labelFr: 'PAC / Rooftop',
    labelEn: 'Heat Pump / Rooftop',
    icon: '🔥',
    descFr: 'Pompes a chaleur, rooftops, unites exterieures, serres',
    descEn: 'Heat pumps, rooftops, outdoor units, greenhouses',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['GLACIAR MIDI', 'GLACIAR MICRO']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['R32', 'R410A', 'R290', 'R454B', 'R454C']),
    applicableSpaceTypes: JSON.stringify(['rooftop', 'technical_room']),
    sortOrder: 8,
  },
  {
    id: 'marine',
    labelFr: 'Marine / Naval',
    labelEn: 'Marine / Shipboard',
    icon: '🚢',
    descFr: 'Salles machines navales, espaces cargaison, refrigeration maritime',
    descEn: 'Ship engine rooms, cargo spaces, marine refrigeration systems',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: true,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5 Direct Sensor Module', 'X5 Remote Sensor', 'GLACIAR MIDI']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R717', 'R744', 'R32', 'R290']),
    applicableSpaceTypes: JSON.stringify(['machinery_room', 'cold_room', 'cold_storage']),
    sortOrder: 9,
  },
  {
    id: 'pharma_lab',
    labelFr: 'Laboratoire / Pharma',
    labelEn: 'Laboratory / Pharmaceutical',
    icon: '🧪',
    descFr: 'Laboratoires, pharma, clean rooms, ultra-basse temperature',
    descEn: 'Laboratories, pharmaceutical, clean rooms, ultra-low temperature',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['GLACIAR MIDI', 'GLACIAR RM']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R744', 'R32', 'R134A']),
    applicableSpaceTypes: JSON.stringify(['office', 'cold_room', 'technical_room']),
    sortOrder: 10,
  },
  {
    id: 'food_processing',
    labelFr: 'Agroalimentaire / Abattoir',
    labelEn: 'Food Processing / Slaughterhouse',
    icon: '🥩',
    descFr: 'Abattoirs, usines agroalimentaires, gros systemes NH3',
    descEn: 'Food processing, slaughterhouses, meat plants, large NH3 systems',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5 Direct Sensor Module', 'X5 Remote Sensor', 'GLACIAR MIDI']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['R717', 'R744']),
    applicableSpaceTypes: JSON.stringify(['cold_room', 'cold_storage', 'machinery_room', 'loading_dock']),
    sortOrder: 11,
  },
  {
    id: 'transport',
    labelFr: 'Transport Refrigere',
    labelEn: 'Refrigerated Transport',
    icon: '🚛',
    descFr: 'Containers frigorifiques, camions, wagons, unites mobiles',
    descEn: 'Refrigerated containers, trucks, rail cars, mobile units',
    accessCategory: 'c',
    locationClass: 'IV',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['GLACIAR MIDI']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['R32', 'R134A', 'R744', 'R404A']),
    applicableSpaceTypes: JSON.stringify(['cold_storage']),
    sortOrder: 12,
  },
];
