// Application seed data — merges identity + M1 regulatory defaults + M2 selection defaults

export const APPLICATIONS = [
  {
    id: 'supermarket',
    labelFr: 'Supermarche / Commerce',
    labelEn: 'Supermarket / Retail',
    icon: '🛒',
    descFr: 'Meubles froids, vitrines refrigerees',
    descEn: 'Refrigerated displays, cold cabinets',
    // M1 defaults
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    // M2 defaults
    productFamilies: JSON.stringify(['MIDI', 'MP']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['co2', 'hfc1', 'hfc2']),
    sortOrder: 1,
  },
  {
    id: 'cold_room',
    labelFr: 'Chambre froide / Entrepot',
    labelEn: 'Cold Room / Warehouse',
    icon: '🧊',
    descFr: 'Stockage refrigere, entrepots frigorifiques',
    descEn: 'Refrigerated storage, cold warehouses',
    accessCategory: 'c',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['MIDI', 'MP']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['co2', 'hfc1', 'hfc2']),
    sortOrder: 2,
  },
  {
    id: 'machinery_room',
    labelFr: 'Salle des machines',
    labelEn: 'Machine Room',
    icon: '⚙️',
    descFr: 'Salle technique avec compresseurs, groupes froids',
    descEn: 'Technical room with compressors, chillers',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5', 'GXR', 'GEX']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['co2', 'hfc1', 'hfc2', 'nh3', 'r290']),
    sortOrder: 3,
  },
  {
    id: 'cold_storage',
    labelFr: 'Entrepot frigorifique',
    labelEn: 'Cold Storage Warehouse',
    icon: '🏭',
    descFr: 'Grands entrepots frigorifiques industriels',
    descEn: 'Large industrial cold storage facilities',
    accessCategory: 'c',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['X5', 'MIDI', 'TR']),
    defaultRanges: JSON.stringify({ R717: '0-100ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2', 'hfc1']),
    sortOrder: 4,
  },
  {
    id: 'parking',
    labelFr: 'Parking souterrain',
    labelEn: 'Underground Parking',
    icon: '🅿️',
    descFr: 'Detection CO/NO2 dans parkings fermes',
    descEn: 'CO/NO2 detection in enclosed parking',
    accessCategory: 'b',
    locationClass: 'III',
    belowGround: true,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5']),
    defaultRanges: JSON.stringify({ CO: '0-100ppm', NO2: '0-5ppm' }),
    suggestedGases: JSON.stringify(['co', 'no2']),
    sortOrder: 5,
  },
  {
    id: 'hotel',
    labelFr: 'Hotel / Confort',
    labelEn: 'Hotel / Comfort',
    icon: '🏨',
    descFr: 'Systemes VRF, espaces occupes, hotels',
    descEn: 'VRF systems, occupied spaces, hotels',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['RM']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc1', 'hfc2']),
    sortOrder: 6,
  },
  {
    id: 'office',
    labelFr: 'Bureau / Tertiaire',
    labelEn: 'Office / Commercial',
    icon: '🏢',
    descFr: 'Bureaux, espaces commerciaux, climatisation',
    descEn: 'Offices, commercial spaces, air conditioning',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['RM']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc1', 'hfc2']),
    sortOrder: 7,
  },
  {
    id: 'ice_rink',
    labelFr: 'Patinoire',
    labelEn: 'Ice Rink',
    icon: '⛸️',
    descFr: 'Patinoires, systemes NH3/CO2',
    descEn: 'Ice rinks, NH3/CO2 systems',
    accessCategory: 'a',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['X5', 'TR']),
    defaultRanges: JSON.stringify({ R717: '0-500ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2']),
    sortOrder: 8,
  },
  {
    id: 'heat_pump',
    labelFr: 'PAC / Rooftop',
    labelEn: 'Heat Pump / Rooftop',
    icon: '🔥',
    descFr: 'Pompes a chaleur, rooftops, R32/R290',
    descEn: 'Heat pumps, rooftops, R32/R290',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['MIDI', 'G']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc2', 'r290']),
    sortOrder: 9,
  },
  {
    id: 'water_brine',
    labelFr: 'Eau glycolee / Saumure',
    labelEn: 'Water / Brine',
    icon: '💧',
    descFr: 'Detection NH3 dans eau ou saumure',
    descEn: 'NH3 detection in water or brine',
    accessCategory: 'c',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['AQUIS']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['nh3']),
    sortOrder: 10,
  },
  {
    id: 'data_center',
    labelFr: 'Data Center',
    labelEn: 'Data Center',
    icon: '🖥️',
    descFr: 'Refroidissement serveurs, salles informatiques',
    descEn: 'Server cooling, IT rooms',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: false,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['MIDI', 'X5']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['hfc1', 'hfc2', 'co2']),
    sortOrder: 11,
  },
  {
    id: 'marine',
    labelFr: 'Marine / Naval',
    labelEn: 'Marine / Shipboard',
    icon: '🚢',
    descFr: 'Salles machines navales, espaces cargaison, refrigeration maritime',
    descEn: 'Ship engine rooms, cargo spaces, marine refrigeration systems',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: true,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5', 'MIDI', 'GXR']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2', 'hfc1', 'r290']),
    sortOrder: 12,
  },
  {
    id: 'hospital',
    labelFr: 'Hopital / Sante',
    labelEn: 'Hospital / Healthcare',
    icon: '🏥',
    descFr: 'Hopitaux, cliniques, blocs operatoires, VRF medical',
    descEn: 'Hospitals, clinics, operating rooms, medical VRF systems',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['RM', 'MIDI']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc1', 'hfc2', 'co2']),
    sortOrder: 13,
  },
  {
    id: 'school',
    labelFr: 'Ecole / Universite',
    labelEn: 'School / University',
    icon: '🏫',
    descFr: 'Ecoles, universites, PAC R-290, climatisation salles de classe',
    descEn: 'Schools, universities, R-290 heat pumps, classroom HVAC',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['RM', 'MIDI']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc2', 'r290']),
    sortOrder: 14,
  },
  {
    id: 'arena',
    labelFr: 'Stade / Arena',
    labelEn: 'Stadium / Arena',
    icon: '🏟️',
    descFr: 'Stades, arenas, grandes surfaces avec patinoire integree',
    descEn: 'Stadiums, arenas, large venues with integrated ice rink',
    accessCategory: 'a',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5', 'MIDI', 'TR']),
    defaultRanges: JSON.stringify({ R717: '0-500ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2', 'hfc1']),
    sortOrder: 15,
  },
  {
    id: 'brewery',
    labelFr: 'Brasserie / Cave a vin',
    labelEn: 'Brewery / Winery',
    icon: '🍺',
    descFr: 'Brasseries, caves a vin, fermentation, froid process',
    descEn: 'Breweries, wineries, fermentation rooms, process cooling',
    accessCategory: 'c',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['X5', 'MIDI']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2']),
    sortOrder: 16,
  },
  {
    id: 'food_processing',
    labelFr: 'Agroalimentaire / Abattoir',
    labelEn: 'Food Processing / Slaughterhouse',
    icon: '🥩',
    descFr: 'Abattoirs, usines agroalimentaires, gros systemes NH3',
    descEn: 'Slaughterhouses, food plants, large NH3 systems',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5', 'GXR', 'TR']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2']),
    sortOrder: 17,
  },
  {
    id: 'pharma_lab',
    labelFr: 'Laboratoire / Pharma',
    labelEn: 'Laboratory / Pharmaceutical',
    icon: '🧪',
    descFr: 'Laboratoires, pharma, clean rooms, ultra-basse temperature',
    descEn: 'Laboratories, pharmaceutical, clean rooms, ultra-low temperature',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['MIDI', 'RM']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['co2', 'hfc1', 'hfc2']),
    sortOrder: 18,
  },
  {
    id: 'industrial_process',
    labelFr: 'Process Industriel',
    labelEn: 'Industrial Process Cooling',
    icon: '🏗️',
    descFr: 'Refroidissement process, petrochimie, chimie',
    descEn: 'Process cooling, petrochemical, chemical plants',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5', 'GXR', 'GEX']),
    defaultRanges: JSON.stringify({ R717: '0-1000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2', 'hfc1', 'r290']),
    sortOrder: 19,
  },
  {
    id: 'transport_reefer',
    labelFr: 'Transport Refrigere',
    labelEn: 'Refrigerated Transport',
    icon: '🚛',
    descFr: 'Containers frigorifiques, camions frigo, wagons',
    descEn: 'Reefer containers, refrigerated trucks, rail cars',
    accessCategory: 'c',
    locationClass: 'IV',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['MIDI', 'G']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc1', 'co2']),
    sortOrder: 20,
  },
  {
    id: 'residential',
    labelFr: 'Residentiel / Domestique',
    labelEn: 'Residential / Domestic',
    icon: '🏠',
    descFr: 'PAC domestiques R-290/R-32, climatisation residentielle',
    descEn: 'Domestic heat pumps R-290/R-32, residential air conditioning',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    productFamilies: JSON.stringify(['RM', 'G']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc2', 'r290']),
    sortOrder: 21,
  },
  {
    id: 'cruise_yacht',
    labelFr: 'Croisiere / Yacht',
    labelEn: 'Cruise Ship / Yacht',
    icon: '🛳️',
    descFr: 'Navires de croisiere, yachts, climatisation + refrigeration embarquee',
    descEn: 'Cruise ships, yachts, onboard HVAC and refrigeration',
    accessCategory: 'a',
    locationClass: 'II',
    belowGround: true,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: true,
    productFamilies: JSON.stringify(['MIDI', 'X5', 'RM']),
    defaultRanges: JSON.stringify({ R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['hfc1', 'hfc2', 'co2']),
    sortOrder: 22,
  },
  {
    id: 'greenhouse',
    labelFr: 'Serre / Agriculture',
    labelEn: 'Greenhouse / Agriculture',
    icon: '🌿',
    descFr: 'Serres, stockage fruits, agriculture controlee',
    descEn: 'Greenhouses, fruit storage, controlled atmosphere agriculture',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    productFamilies: JSON.stringify(['X5', 'MIDI']),
    defaultRanges: JSON.stringify({ R717: '0-500ppm', R744: '0-10000ppm' }),
    suggestedGases: JSON.stringify(['nh3', 'co2']),
    sortOrder: 23,
  },
  {
    id: 'power_plant',
    labelFr: 'Centrale Electrique / Turbine',
    labelEn: 'Power Plant / Turbine Cooling',
    icon: '⚡',
    descFr: 'Refroidissement generateurs, turbines, transformateurs',
    descEn: 'Generator cooling, turbine cooling, transformer cooling',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    productFamilies: JSON.stringify(['X5', 'GXR']),
    defaultRanges: JSON.stringify({}),
    suggestedGases: JSON.stringify(['hfc1', 'hfc2']),
    sortOrder: 24,
  },
];
