export const SPACE_TYPES = [
  {
    id: 'sales_area',
    labelFr: 'Espace de vente',
    labelEn: 'Sales Area',
    icon: '🛒',
    accessCategory: 'a',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    sortOrder: 1,
  },
  {
    id: 'cold_room',
    labelFr: 'Chambre froide',
    labelEn: 'Cold Room',
    icon: '❄️',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 2,
  },
  {
    id: 'machinery_room',
    labelFr: 'Salle des machines',
    labelEn: 'Machinery Room',
    icon: '⚙️',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    sortOrder: 3,
  },
  {
    id: 'cold_storage',
    labelFr: 'Entrepôt frigorifique',
    labelEn: 'Cold Storage',
    icon: '🏭',
    accessCategory: 'b',
    locationClass: 'II',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 4,
  },
  {
    id: 'technical_room',
    labelFr: 'Local technique',
    labelEn: 'Technical Room',
    icon: '🔧',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 5,
  },
  {
    id: 'office',
    labelFr: 'Bureau',
    labelEn: 'Office',
    icon: '🏢',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 6,
  },
  {
    id: 'hotel_room',
    labelFr: 'Chambre d\'hôtel',
    labelEn: 'Hotel Room',
    icon: '🏨',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 7,
  },
  {
    id: 'loading_dock',
    labelFr: 'Quai de chargement',
    labelEn: 'Loading Dock',
    icon: '🚛',
    accessCategory: 'a',
    locationClass: 'IV',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 8,
  },
  {
    id: 'parking',
    labelFr: 'Parking souterrain',
    labelEn: 'Underground Parking',
    icon: '🅿️',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: true,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    sortOrder: 9,
  },
  {
    id: 'ice_rink',
    labelFr: 'Patinoire',
    labelEn: 'Ice Rink',
    icon: '⛸️',
    accessCategory: 'a',
    locationClass: 'I',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: true,
    humanComfort: true,
    c3Applicable: true,
    mechVentilation: false,
    sortOrder: 10,
  },
  {
    id: 'rooftop',
    labelFr: 'Toiture / Extérieur',
    labelEn: 'Rooftop / Outdoor',
    icon: '☀️',
    accessCategory: 'b',
    locationClass: 'IV',
    belowGround: false,
    isMachineryRoom: false,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: false,
    sortOrder: 11,
  },
  {
    id: 'basement_machinery',
    labelFr: 'Sous-sol machinerie',
    labelEn: 'Basement Machinery',
    icon: '⬇️',
    accessCategory: 'c',
    locationClass: 'III',
    belowGround: true,
    isMachineryRoom: true,
    isOccupiedSpace: false,
    humanComfort: false,
    c3Applicable: false,
    mechVentilation: true,
    sortOrder: 12,
  },
];
